### PR TITLE
HOP-3582 : Properties Input always requires a file

### PR DESCRIPTION
**Pull request by uraychang**
Following this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
       where you replace `HOP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). 
In this case, just format the pull request title like `(DOC) - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://hop.apache.org/community/contributing/)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hansva** [comment]
Hi @uraychang I did some tests and though you did fix most of it there is one case that is still failing and should work.
When only a single file has been added but it points to a non existing file and required is set to N then the transform should not fail and just finish as successful.

I added an example pipeline 0041-properties-file-input-invalid-file-required-no.hpl

image

Then you get following error:

```
2022/01/24 21:32:57 - read non existing file required N.0 - ERROR: Unexpected error
2022/01/24 21:32:57 - read non existing file required N.0 - ERROR: org.apache.hop.core.exception.HopException: 
2022/01/24 21:32:57 - read non existing file required N.0 - No file(s) specified! Stop processing.
2022/01/24 21:32:57 - read non existing file required N.0 - 
2022/01/24 21:32:57 - read non existing file required N.0 - 	at org.apache.hop.pipeline.transforms.propertyinput.PropertyInput.processRow(PropertyInput.java:68)
2022/01/24 21:32:57 - read non existing file required N.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:58)
2022/01/24 21:32:57 - read non existing file required N.0 - 	at java.lang.Thread.run(Thread.java:748)
````

When the required flag is set to Y it should fail (and this works)

**Comment by uraychang** [comment]
Thanks for the test!
Will take a look recently.

**Review by uraychang — COMMENTED** [review]
Hi Hans, thanks for fixing this. May I know how you find the root cause? Why it can be executed without any problem on GUI?

**Comment by hansva** [comment]
The test does not allocate the length of the requiredFile object correctly and the regular flow does.
It's not the prettiest code

**Comment by uraychang** [comment]
Got it! thanks

**Pull request merged**
