### PR TITLE
(DOC) more fixes in workflow/actions/workflow

### PR DESCRIPTION
**Pull request by VladimirAlexiev**
A couple more fixes to workflow/actions/workflow (see #1563)
- @hansva how to fix the bullets in `You can do this by:` to appear as list items? Maybe that's impossible in a table cell?

### CODE REVIEW

**Comment by VladimirAlexiev** [comment]
fixes list `You can do this by:` using syntax from https://github.com/apache/hop/edit/master/docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jsoninput.adoc line 39

**Comment by hansva** [comment]
yep, you beat me to it was just fixing it. Don't ask my why but you need to add an 'a' in front of the cell start

**Comment by hansva** [comment]
for more info on this https://docs.asciidoctor.org/asciidoc/latest/tables/format-cell-content/#a-operator

**Comment by hansva** [comment]
My diff was being weird because it was merging your and my changes, I pushed the 'a' you can see it on line 36 of the jsoninput.adoc too.
Screenshot 2022-07-06 at 10 33 20

**Comment by VladimirAlexiev** [comment]
Thanks @hansva I'll know for the future!

@gitmstoute can you weigh in on formatting of lists in tables?
In https://github.com/apache/hop/pull/1558/files you use `+` at the end of line?

**Pull request merged**
