### PR TITLE
HOP-4510: Fix Move Files action error on Windows

### PR DESCRIPTION
**Pull request by wAVeckx**
This pull request is meant to fix the movefiles action

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hansva** [comment]
I would have to dig in the code and check...
But It seems that the "else" block should just be removed from that if/elseif block.
Except for the Azure types all other files should just be handled like the used to be handled.

**Comment by wAVeckx** [comment]
I originally thought of doing that but assumed there was a reason for it being added in recently. Would you like me to adjust the code in the PR for this?

**Comment by hansva** [comment]
Yes please, feel free to do so. Thanks for the PR @wAVeckx !

**Comment by wAVeckx** [comment]
Let me know if you have any further adjustment you would like to see made with this PR.

**Pull request merged**
