### PR TITLE
Incorrect tooltip position #4252

### PR DESCRIPTION
**Pull request by ep9io**
The pull request sets the `GDK_BACKEND` environment variable is explicitly set to `x11` when wayland is detected. This forces GTK-based HOP to use X11 rendering, making it compatible in Wayland sessions.   The rest of the Linux-specific logic related to classpath and architecture is preserved as-is.

Below is a screenshot showing the issue resolved when `GDK_BACKEND=x11` is applied and the mouse is hovered over the hop line near the success instead of the top-left corner.

image

NOTE:  This pull request also addresses related issues spotted when hovering over pipeline arrows, the welcome dialog and other dialogs appearing in the top-left of the screen.

**Additional Information:**

The issue was reproduced on Fedora 39 running Wayland and goes away with the attached pull request.

The issue appears to be related to SWT/GDK when on Wayland (see eclipse tickets below).

* https://github.com/eclipse-platform/eclipse.platform.swt/issues/639
* https://github.com/eclipse-platform/eclipse.platform.swt/issues/790

Can't confirm if related or if it resolves issue https://github.com/apache/hop/issues/4441.

In addition, an observation with the dialogs in that adding `ON_TOP` to the style mitigates, but does not eliminate the issue.  This was obtained from https://github.com/eclipse-platform/eclipse.platform.swt/issues/790.

`shell = new Shell(parent, SWT.ON_TOP | SWT.DIALOG_TRIM | SWT.CLOSE | SWT.RESIZE | SWT.MAX);`

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by ep9io** [comment]
Only after noticing that the PR also included 26e38a5eeea6f6270ca454b626a5e0099f22eeee and 00a3249236544fe38e4aaf892810ffb460b5e2b9, which should not cause an issue.  I branched off a development branch that I keep locally.

**Comment by hansva** [comment]
awesome @ep9io !

**Comment by ep9io** [comment]
It's really only a workaround.   The issue with not running properly under Wayland is still there, however.

**Comment by hansva** [comment]
Yes, but reading the tickets it seems like an SWT issue so we can't really do much about it on our side.

**Pull request merged**
