### PR TITLE
Fields tab in Text File Output transform (UI Bug) #4436

### PR DESCRIPTION
**Pull request by nadment**

### CODE REVIEW

**Comment by hansva** [comment]
seems this was the cause:
```
    lsResize =
        event -> {
          Point size = shell.getSize();
          wFields.setSize(size.x - 10, size.y - 50);
          wFields.table.setSize(size.x - 10, size.y - 50);
          wFields.redraw();
        };
    shell.addListener(SWT.Resize, lsResize);
```

**Comment by hansva** [comment]
@nadment , could you test this on windows and then feel free to merge.

**Comment by nadment** [comment]
@hansva it's possible  you talk about an other issues #4441 ?

**Comment by hansva** [comment]
No I am not, this listener was hidden in the text file output
https://github.com/apache/hop/pull/4438/files#diff-c785c5464a0ac8645599379fb00b7b50cb788534af69e146f2bcf4e566626154L1251-L1259

**Comment by nadment** [comment]
Work fine on Windows OS.
Good point, I hadn't seen this resize part of the code. 
The setButtonPositions method also posed a problem because it works with the shell and not with a composite parent.

**Pull request merged**
