### PR TITLE
HOP-4192 Fixed org.eclipse.swt.graphics.Color compatibility

### PR DESCRIPTION
**Pull request by shlxue**

### CODE REVIEW

**Comment by hansva** [comment]
which OS was this tested on and can I get before and after pictures, makes the PR simpler to evaluate.

**Comment by shlxue** [comment]
web HopGui:
1. docker run -it -p 8081:8080 apache/hop-web:2.1.0-SNAPSHOT
2. open url:http://localhost:8081/ui

**Comment by shlxue** [comment]
Error-when-open-hop-gui
Color-class-in-RAP

**Comment by shlxue** [comment]
Color-construcotr-methods

**Comment by hansva** [comment]
ah, an error in Hop Web! thanks!

**Pull request merged**
