### PR TITLE
Make the 'log' object private in ActionBase and BaseTransformMeta #4348

### PR DESCRIPTION
**Pull request by nadment**

### CODE REVIEW

**Comment by hansva** [comment]
In the Integration tests I am getting error lines but they are not stopping the execution (also not getting a full stacktrace):
`at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.isRowLevel(TableOutput.java:431)`
Will have to see if we can find the cause and if there are more of these

**Comment by hansva** [comment]
Ah, the issue is very obvious....

**Comment by nadment** [comment]
This case should neither compile nor pass unit tests, and yet I'm sure I've tested a complete and clean installation. A mystery?

**Comment by hansva** [comment]
sorry the link is coming from the master branch which does not have your changes yet.
the actual code is.

```
  @Override
  public boolean isRowLevel() {
    return isRowLevel();
  }
```
Which is valid code and compiles but it's just a never-ending self reference

**Comment by nadment** [comment]
I'm going to temporarily put the methods in final to find these cases.

**Comment by nadment** [comment]
TableOutup is the only case I've found with an infinite loop. There is a special case with Janino that overrides the logXXX() methods, but it seems OK.

**Pull request merged**
