### PR TITLE
Add option -v --version to print version in the CLI #2153

### PR DESCRIPTION
**Pull request by nadment**
Add option -v --version to print version in the CLI:
- hop-conf
- hop-run
- hop-search
- hop-import

### CODE REVIEW

**Comment by hansva** [comment]
This PR requires a Documentation change too

**Comment by hansva** [comment]
Code looks fine, maybe we have to figure out a way to add the builddate when it's a snapshot version. Though we have to be careful not to break other logic (eg. logic for documentation URL's)

**Comment by nadment** [comment]
I don't know how to add the build date when it's a snapshot version, probably something to add in the build process?

**Comment by hansva** [comment]
I'll try and take a look at it, thanks for the work @nadment !

**Pull request merged**
