### PR TITLE
Add Cyclonedx SBOM during release, #4235

### PR DESCRIPTION
**Pull request by hansva**
Added the cyclonedx maven plugin to generate SBOM files.

Placed the plugin into a profile that will only be executed during our release process.
The SBOM generation does take quite some additional CPU time.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by dsanderbi** [comment]
Hi @hansva ,
Maybe I'm overlooking something, but unfortunately, the bom.json is not part of the latest release of Apache Hop 2.11. I can't find it in apache-hop-client-2.11.0.zip.

**Comment by hansva** [comment]
Hi @dsanderbi it's not included in the client zip but is available on [maven central  ](https://repo1.maven.org/maven2/org/apache/hop/hop-client/2.11.0/)

**Comment by hansva** [comment]
Maybe we should change our release process and add the file to the download page too

**Comment by dsanderbi** [comment]
@hansva thank you for the info!
It would be great to include the bom to the download page.

**Comment by dsanderbi** [comment]
Hi @hansva 

i can't find the SBOM file, has the location changed?
Only 2.10 & 2.11 is present.

https://repo1.maven.org/maven2/org/apache/hop/hop-client/

{1691E57D-66BD-47C0-B9FA-3531286C3C1C}

Is there any update if you will add the SBOM to the download page?

**Pull request merged**
