### PR TITLE
[HOP-3889] - Support apache doris stream bulk load insert/update records into doris

### PR DESCRIPTION
**Pull request by XiaotaoYi**
[HOP-3889] - Support apache doris stream bulk load insert/update records into doris

Following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/HOP) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[HOP-XXX] - Fixes bug in SessionManager`,
       where you replace `HOP-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`. 
 
Trivial changes like typos do not require a JIRA issue (javadoc, comments...). 
In this case, just format the pull request title like `(DOC) - Add javadoc in SessionManager`.
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://hop.apache.org/community/contributing/)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by hansva** [comment]
Thank you for the contribution @XiaotaoYi !

**Comment by XiaotaoYi** [comment]
> Thank you for the contribution @XiaotaoYi !

It's my pleasure!

**Comment by XiaotaoYi** [comment]
please hold the approve, I am trying to double check on on local

**Comment by XiaotaoYi** [comment]
It's okay now, the change code was built and run pache-rat:check successfully in my local.

**Comment by hansva** [comment]
thanks @XiaotaoYi , I'll try to give it a test and merge as soon as possible

**Review by hf200012 — APPROVED** [review]
LGTM

**Comment by hansva** [comment]
do you have a docker container to test this against?

**Comment by mattcasters** [comment]
I'll merge this code and then I'll do some cleanup on the metadata side.

**Comment by hansva** [comment]
This PR has been continued in #1495

**Pull request closed without merging**
