### PR TITLE
Fix Action Bulk load into MSSQL to support native connection #3693

### PR DESCRIPTION
**Pull request by nadment**
Not tested !

### CODE REVIEW

**Comment by hansva** [comment]
waiting for response from @alexismorison95 before merge.

**Comment by alexismorison95** [comment]
> waiting for response from @alexismorison95 before merge.

I can't compile Apache HOP in my computer, sorry :(

**Comment by usbrandon** [comment]
[hop-assemblies-plugins-action-mssqlbulkload-2.8.0-SNAPSHOT.zip](https://github.com/apache/hop/files/14566614/hop-assemblies-plugins-action-mssqlbulkload-2.8.0-SNAPSHOT.zip)
This did work for me using MS SQL 2019 and the native JDBC driver, however due to my docker container using MS SQL 2019 and Hop being in Windows, I could not get the bulkload action in the workflow to work. 

 @alexismorison95 can you replace the plugins/action/mssqlbulkload with the contents of this zip file then give it a try?

**Comment by hansva** [comment]
let's merge and then in a couple of hours it can be tested with a build from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.9.0-SNAPSHOT/)

**Pull request merged**
