### PR TITLE
fix #3867

### LINKED ISSUE #3867: [Feature Request]: Unit test action: dialog improvement
### What would you like to happen?

Instead of always pressing the _Get tests name_ button and starting from the entire list of tests to retrieve the test we need to run, it would be nice to have a combo to select the test from

### Issue Priority

Priority: 3

### Issue Component

Component: Other

### PR DESCRIPTION
**Pull request by sramazzina**
fix #3867 - Unit test action: dialog improvement

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [x] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [x] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by sramazzina** [comment]
@hansva sorry for the wrong label name I've not noticed :-(. I will change it

**Comment by sramazzina** [comment]
@hansva, unfortunately, the only thing I'm able to fix is the label. Multiple selection (that I agree with you is not completed in the EnterSelectionDialog therefore it cannot be used. About the hieght of the dialog I'm to find out a way to set the height of the dialog but it seems not that easy. Let me know your opinion about confirming to move forward with this improvement or if we want to throw everything away and leave the things as they are.

**Comment by hansva** [comment]
As stated in my previous comment, nothing you can do about it in this ticket. Just some personal frustration flowing out.
Thanks for the change LGTM

**Comment by sramazzina** [comment]
Yeah I understand and I agree with you

**Comment by hansva** [comment]
right, a mixup happened in the issue number, for reference this is for #3867

**Pull request merged**
