### PR TITLE
Integrate with and prompt various language models through popular platforms (OpenAI, Anthropic, Hugging Face, Mistral, Ollama) #4396

### PR DESCRIPTION
**Pull request by ep9io**
The ability for Apache HOP to integrate with and prompt various language models. This feature should support models hosted on popular platforms such as OpenAI, Anthropic, Hugging Face, and Mistral. Additionally, include the capability to interface with locally hosted models via Ollama,

Resubmitting original PR, previous was accidentally requested from incorrect branch (master instead of pr/4396-...).
Recent change since initial PR: Added a sample that demonstrates fact-checking on grounding documents.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by bamaer — COMMENTED** [review]
Added a couple of missing ASF headers. Other than that, this looks good. 
There's quite a bit of commented code in `LanguageModelFacade.java` and other classes. If this code is not required at this point, would you mind removing it?

**Comment by ep9io** [comment]
> There's quite a bit of commented code in `LanguageModelFacade.java` and other classes. If this code is not required at this point, would you mind removing it?

I've removed any commented out code that is not needed.  Also made some minor adjustments while scanning over the code.

**Comment by hansva** [comment]
I will remove the `loadXml` and `getXml` methods. But this is great work!

**Comment by hansva** [comment]
Thanks so much for the work @ep9io , We will add a shoutout to the release notes

**Comment by ep9io** [comment]
> Thanks so much for the work @ep9io , We will add a shoutout to the release notes

@hansva No problem at all! 

I'm glad I could contribute back, and I hope the functionality proves useful to others, even though the project this code was written for has pretty much come to an end. I still plan to contribute to the plugin with samples, documentation, and more now that it's open source.

**Pull request merged**
