### PR TITLE
[tests](docker)Add the Docker-compose test case yaml file for Apache Doris

### PR DESCRIPTION
**Pull request by FreeOnePlus**
------------------------

I recently supported and optimized Apache Doris's Docker image orchestration work. We had an exchange last year. You hope that we can provide an easy-to-run docker-compose script for connectivity testing. Sorry for the long delay, I have submitted it PR to Master, if you have any questions, you can continue to communicate via email, my email is suyijia@selectdb.com. Good luck.

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:
- [ ] Run `mvn clean install apache-rat:check` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
- [ ] If you have a group of commits related to the same change, please squash your commits into one and force push your branch using `git rebase -i`.
- [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by FreeOnePlus** [comment]
It should be noted that in the ENV parameter in the yaml script, where the local_host parameter is mentioned, it needs to be manually modified to the intranet IP of the current node, or the IP can be specified by building a subnet bridge.

**Comment by hansva** [comment]
thank you so much @FreeOnePlus !

**Comment by FreeOnePlus** [comment]
Can this PR be integrated?

**Comment by hansva** [comment]
Thanks for the PR!

**Pull request merged**
