### PR TITLE
HOP-3826, HOP-3988

### PR DESCRIPTION
**Pull request by nadment**

### CODE REVIEW

**Comment by uraychang** [comment]
hi @nadment, is HopGuiEvents.ProjectUpdated used somewhere else?
I saw HopGuiEvents.ProjectActivated was triggered when enabling the project.
but is adding HopGuiEvents.ProjectUpdated listener necessary?

**Comment by nadment** [comment]
You are right @uraychang , HopGuiEvents.ProjectUpdate is never triggered, but it should be when editing a project path

**Comment by uraychang** [comment]
@nadment great!

**Review by uraychang — APPROVED** [review]
@nadment great work!
sorry I misclick the close button...

**Pull request merged**
